service: serverless-chart-processor

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-west-1

functions:
  server:
    handler: index.server
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
